### ISSUE TITLE
mac example not compiling

### ISSUE THREAD

**Issue by araid** [simongeilfus/SpacePartitioning#1]
The mac exemple is missing the _prefix file as well as an `#include "cinder/Exception.h"` in the header file.
This block looks great btw, looking forward to more examples :D

**Comment by simongeilfus** [comment]
Hey, thanks for reporting this.
I didn't pay too much attention when creating the repo but it looks like github default .gitignore has precompiled headers in it : https://github.com/simongeilfus/SpacePartitioning/blob/master/.gitignore#L9

Good thing to know!

I'll make sure to update that in the next commit!

**Comment by simongeilfus** [comment]
Should be fixed!
