### ISSUE TITLE
Number of points in a structure?

### ISSUE THREAD

**Issue by richardeakin** [simongeilfus/SpacePartitioning#3]
It looks like they all have a method on them called `size()`, but it is documented as returning the 'size in terms of bytes'. I'd like to know instead how many points have been added to a Grid, for example.

Also I think its nice to be consistent with STL in this case, where `size()` indicates how many elements and to get the number of bytes you'd typically do `grid.size() * sizeof( vec3 )` (or add a method called sizeBytes() for convenience).

**Comment by simongeilfus** [comment]
Totally agree.
I think I added this function while doing some benchmarks but I'll definitely change that in the next update.

**Comment by simongeilfus** [comment]
This should be addressed here: https://github.com/simongeilfus/SpacePartitioning/commit/1364dd7bf1de7ae42e6c83833bb4f1467f00412e
